% Petri Nets Toolbox.
% Version 1.0b   1-Sep-00
% Copyright (c) Zdenek Hanzalek, Martina Svadova, 
%   
% Petri nets Tolbox
%
% Disp_gr.m		Displays the graph og reachable markings
% EvolGr.m		Calculation of matrix of evolution graph for continuous Petri nets with constant speed
% Getnum.m		Convert numerical part of string to number
% Getpnt.m		Find out type of transmission
% Graph.m		Finds adjancency matrix A an matrix reachable markings B
% GraphPri.m		Finds a graph of reachable markings to given marked bounded Priority Petri Net
% Ind.m			Gets indexes of rows and columns
% PlaySTPN.m		Token player for T-timed PNs and stochastic PNs, single firing semantic
% PlaySTPNex.m		Token player for T-timed PNs and stochastic PNs, single firing semantic, list of state in each time
% Rdp.m			Reads matrix Pre, Post, initial marking from graphical editor PMEdit
% Rdp2stpn.m		Reads matrix Pre, Post, initial marking, type of transition, times of timed transition
%			from graphical editor PMEdit ( input parameters for PlaySTPN)
% Rdp2pri.m		Reads matrix Pre, Post, initial marking, type of transition, times of timed transition
%			and priority of transition from graphical editor PMEdit (input parameters for GraphPri)
%			This function must be also used when we want to read parameters of continuous Petri net, 
%			where parameter PrioT is equivalent to V (vector maximal speed in CPN)
% Silva.m		Gets P-invariants of PNs

	


